export const COLORS = {
  DARK: "#021C35",
  LIGHT_DARK: "#35587a",
  LIGHT: "#87CEFA",
  ERROR_COLOR: "#b14040",
  SUCCESS_COLOR: "#52952f",
  WARNING_COLOR: "#F0E68C",
};

export const G_API_KEY = "...";

export const LANG = "en";
export const REG = "pl";

export const DAY_PREV = {
  Mon: "Sun",
  Tue: "Mon",
  Wed: "Tue",
  Thu: "Wed",
  Fri: "Thu",
  Sat: "Fri",
  Sun: "Sat",
};

export const DAY_NUM = {
  Mon: 0,
  Tue: 1,
  Wed: 2,
  Thu: 3,
  Fri: 4,
  Sat: 5,
  Sun: 6,
};

export const DAY_NUM_TO_PREV_NUM = [6, 0, 1, 2, 3, 4, 5];
export const DAY_NUM_TO_NEXT_NUM = [1, 2, 3, 4, 5, 6, 0];

export const DAY_NEXT = {
  Mon: "Tue",
  Tue: "Wed",
  Wed: "Thu",
  Thu: "Fri",
  Fri: "Sat",
  Sat: "Sun",
  Sun: "Mon",
};

export const txt = {
  gb: {
    header: {
      all: "all",
      map: "map",
      info: "info",
      profile: "profile",
      login: "login",
      categories: "categories",
      allDd: "All",
      search: "search",
      home: "home",
      logout: "logout",
      language: "lang",
      cities: "cities",
      filters: "filters",
    },
    block: {
      type: "type",
      hours: "hours",
      distance: "distance",
      address: "address",
      online: "online",
      km: "km",
    },
    company: {
      stream: "stream",
      schedule: "schedule",
      description: "description",
      contacts: "contacts",
      gallery: "gallery",
      name: "name",
      type: "type",
      hours: "hours",
      distance: "distance",
      address: "address",
      Mon: "Mon",
      Tue: "Tue",
      Wed: "Wed",
      Thu: "Thu",
      Fri: "Fri",
      Sat: "Sat",
      Sun: "Sun",
      adult: "You must be 18 years or older to view the content of this page",
      yes: "I am 18 or older",
      no: "I am not yet 18 years old",
      worktime: "work time",
      novideo: "this video is disabled",
    },
    login: {
      login: "login",
      password: "password",
    },
    info: {
      "about us": "about us",
      faq: "faq",
      contacts: "contacts",
      name: "name",
      email: "email",
      subject: "subject",
      message: "message",
      send: "send email",
      change: "Change Files",
      upload: "Upload Files",
    },
    list: {
      addplace: "add place",
      settings: "sites & categories",
      logout: "logout",
      name: "name",
      alias: "alias",
      city: "city",
      type: "type",
      delete: "delete",
      create: "create",
      createnew: "create new place",
      yes: "yes",
      hidequestion: "do you realy want to hide",
      password: "password",
      save: "save",
      edituser: "edit user",
      adduser: "add user",
      add: "add",
      delquestion: "do you realy want to delete",
      hide: "hide",
      show: "show",
      olduser: "Old user",
      newuser: "New user",
      places: "All places with this user",
    },
    profile: {
      address: "address",
      name: "name",
      alias: "alias",
      description: "description",
      save: "save",
      cancel: "cancel",
      saveloc: "save location",
      title: "Title",
      value: "value",
      titlebig: "Title (phone, website, ...)",
      valuebig: "Value (https://example.com)",
      main: "main",
      cat: "categories",
      cities: "cities",
      catmaxmin: "categories (max 3 / min 1)",
      toplace: "to the place",
      addnew: "Add new (phone number, website, instagram, ...)",
      gallery: "Gallery",
      properties: "attributes",
      contacts: "Contacts",
      adult: "18+ for alert window",
    },
    settings: {
      cities: "cities",
      name: "name",
      slug: "slug",
      coords: "coords",
      address: "address",
      del: "del",
      cat: "categories",
      addnew: "add new",
      editcity: "edit city",
      lat: "lat",
      lon: "lon",
      save: "save",
      editcat: "edit category",
      createcity: "create city",
      geo: "Geolocation (lat;lon)",
      create: "create",
      createcat: "create new category",
      delcity: "delete city",
      delete: "delete",
      delcat: "delete category",
    },
    stream: {
      notcreated: "stream has not been created yet",
      deletestr: "delete stream",
      link: "Link for RTMP camera",
      createstr: "create stream",
      copylink: "copy link to clipboard",
      notwork: "The video is not working",
      blur: "blur",
      volon: "sound is on",
      voloff: "sound is off",
      streamname: "Stream name",
      ifwant:
        "If you want to add a stream, then contact support on the page info - contacts",
    },
    streamsch: {
      disableto: "Disabled to",
      streamto: "stream to",
      disable: "Disable",
      Mon: "Mon",
      Tue: "Tue",
      Wed: "Wed",
      Thu: "Thu",
      Fri: "Fri",
      Sat: "Sat",
      Sun: "Sun",
      closed: "closed",
      opened: "opened",
      startt: "start time",
      endt: "end time",
      save: "save",
      start: "start",
      end: "end",
      timeto: "timeto",
      notcreated: "stream has not been created yet",
    },
    adminnav: {
      profile: "profile",
      stream: "stream",
      worksch: "work schedule",
      streamsch: "stream schedule",
    },
    drop: {
      changeim: "change image",
      addim: "Click or drag to add an image",
      cancel: "cancel",
      saveim: "save image",
      deleteim: "delete image",
      imagetxt:
        "The profile picture is the first picture in the list below. By clicking on another picture, you make it the main one.",
      max: "You have reached the image maximum.You can delete the old one and upload the new image.",
      desc: "description",
      del: "delete",
      main: "main",
      save: "save",
    },
    err: {
      unrec: "Unrecognized error",
      largeimg: "Large image file",
      image10: "The maximum number of images is 10",
      onlyimg: "Only image file",
      largeonly: "The file too large or not image",
      emailerr: "The Email field is required and must be valid",
      passerr:
        "The PASSWORD field is required and must be at least 8 characters",
      nameerr: "The NAME field is required",
      aliaserr:
        "The ALIAS field is required and must contain only English characters and numbers and can`t be just a numbers.",
      something: "Something went wrong",
      sessionerr: "Session is over",
      socialerr: "The TITLE and VALUE fields are required",
      logpas: "Invalid EMAIL or PASSWORD",
      cat1: "The category is required. Put first the category you need and then delete this one.",
      cat3: "The maximum number of categories is 3.",
      bufer: "successfully copied to clipboard",
      succ: "successfully",
      sentmail: "Name Subject Message fields are required",
      strname: "Stream Name field is required",
      nouser: "user not found",
      olduser: "maybe this user already exists",
    },
    time: {
      h: "h",
      m: "m",
    },
    video: {
      first: "The video is temporarily unavailable",
      second: " Sorry for the inconvenience",
      blur: "blur",
      voloff: "sound is off",
    },
    goback: {
      goback: "Go back",
    },
    politic: {
      main: "By clicking “Accept All Cookies”, you agree to the storing of cookies on your device to enhance site navigation and analyze site usage.",
      activetxt:
        "These cookies are necessary for the website to function and cannot be switched off in our systems. They are usually only set in response to actions made by you which amount to a request for services, such as setting your privacy preferences, logging in or filling in forms. You can set your browser to block or alert you about these cookies, but some parts of the site will not then work.",
      activetxtmain:
        "These cookies do not store any personally identifiable information.",
      lang: "Storing information about the text language you have chosen. For ease of navigation on the site",
      city: "Storing information about the city you have chosen. For the convenience of finding establishments.",
      user: "Storing information about the user entering the personal account. For the convenience of logging into your account.",
      active: "Always Active",
      insettings: "In browser settings",
      warried: "We would be worried about your personal information",
      accept: "Accept All Cookies",
      reject: "Reject All",
      loc: "Geolocation data. When you first enter the site, you are shown a window to consent to use your location. We do not store this data, but only use it to more accurately select establishments and display distance. You can disable this functionality in your browser settings.",
      ok: "Familiarized",
    },
    map: {
      working: "Working",
    },
  },
  pl: {
    header: {
      all: "",
      map: "mapa",
      info: "info",
      profile: "profil",
      login: "zaloguj",
      categories: "kategorie",
      allDd: "Wszystkie",
      search: "szukaj",
      home: "dom",
      logout: "wyloguj",
      language: "Język",
      cities: "miasta",
      filters: "filtry",
    },
    block: {
      type: "typ",
      hours: "godziny",
      distance: "oddalenie",
      address: "adres",
      online: "online",
      km: "km",
    },
    company: {
      stream: "strumień",
      schedule: "rozkład",
      description: "opis",
      contacts: "łączność",
      gallery: "galeria",
      name: "nazwa",
      type: "typ",
      hours: "godziny",
      distance: "oddalenie",
      address: "adres",
      Mon: "Pon",
      Tue: "Wt",
      Wed: "Śr",
      Thu: "Cz",
      Fri: "Pi",
      Sat: "So",
      Sun: "Ni",
      adult: "Aby przeglądać treść tej strony musisz mieć ukończone 18 lat",
      yes: "Mam 18 lat lub więcej",
      no: "Nie mam jeszcze 18 lat",
      worktime: "czas pracy",
      novideo: "ten film jest wyłączony",
    },
    login: {
      login: "zaloguj sie",
      password: "hasło",
    },
    info: {
      "about us": "o nas",
      faq: "faq",
      contacts: "kontakty",
      name: "nazwa",
      email: "email",
      subject: "temat",
      message: "wiadomość",
      send: "wysłać email",
      change: "zmienić pliki",
      upload: "przesłać pliki",
    },
    list: {
      addplace: "dodać miejsce",
      settings: "strony & kategorie",
      logout: "wyloguj",
      name: "nazwa",
      alias: "alias",
      city: "miasto",
      type: "typ",
      delete: "kasować",
      create: "stwórzyć",
      createnew: "stworzyć nowe miejsce",
      yes: "tak",
      hidequestion: "czy naprawdę chcesz się",
      password: "hasło",
      save: "zapisać",
      edituser: "edytować użytkownika",
      adduser: "Dodać użytkownika",
      add: "dodać",
      delquestion: "czy naprawdę chcesz usunąć",
      hide: "ukryć",
      show: "pokazać",
      olduser: "Stary użytkownik",
      newuser: "Nowy użytkownik",
      places: "Wszystkie miejsca z tym użytkownikiem",
    },
    profile: {
      address: "adres",
      name: "nazwa",
      alias: "alias",
      description: "opis",
      save: "zapisać",
      cancel: "anulować",
      saveloc: "zapisać lokalizację",
      title: "Tytuł",
      value: "wartość",
      titlebig: "Tytuł (telefon, strona internetowa, ...)",
      valuebig: "Tytuł (https://example.com)",
      main: "główny",
      cat: "kategorie",
      cities: "miasta",
      catmaxmin: "kategorie (max 3 / min 1)",
      toplace: "do miejsca",
      addnew: "Dodaj nowy (numer telefonu, strona internetowa, instagram, ...)",
      gallery: "Galeria",
      properties: "attrybuty",
      contacts: "Łączność",
      adult: "18+ dla okna alertu",
    },
    settings: {
      cities: "miasta",
      name: "nazwa",
      slug: "slug",
      coords: "współrzędne",
      address: "adres",
      del: "kas",
      cat: "kategorie",
      addnew: "dodać nowe",
      editcity: "edytować miasto",
      lat: "szer",
      lon: "dług",
      save: "zapisać",
      editcat: "edytować kategorię",
      createcity: "stworzyć miasto",
      geo: "Geolokalizacja (szer;dług)",
      create: "stworzyć",
      createcat: "utwórzyć nową kategorię",
      delcity: "kasować miasto",
      delete: "kasować",
      delcat: "kasować kategorię",
    },
    stream: {
      notcreated: "strumień nie został jeszcze utworzony",
      deletestr: "kasować strumień",
      link: "link do RTMP kamery",
      createstr: "utwórzyć strumień",
      copylink: "kopiować link do schowka",
      notwork: "Film nie działa",
      blur: "plama",
      volon: "dźwięk jest włączony",
      voloff: "dźwięk jest wyłączony",
      streamname: "Nazwa strumienia",
      ifwant:
        "Jeśli chcesz dodać strumień, skontaktuj się z pomocą techniczną na stronie info - kontakty",
    },
    streamsch: {
      disableto: "Wyłączony do",
      streamto: "strumień do",
      disable: "Wyłącz",
      Mon: "Pon",
      Tue: "Wt",
      Wed: "Śr",
      Thu: "Cz",
      Fri: "Pi",
      Sat: "So",
      Sun: "Ni",
      closed: "zamknięte",
      opened: "otwierany",
      startt: "czas rozpoczęcia",
      endt: "Koniec czasu",
      save: "zapisać",
      start: "początek",
      end: "koniec",
      timeto: "czas do",
      notcreated: "strumień nie został jeszcze utworzony",
    },
    adminnav: {
      profile: "profil",
      stream: "strumień",
      worksch: "plan pracy",
      streamsch: "plan strumieni",
    },
    drop: {
      changeim: "zmienić obraz",
      addim: "kliknąć lub przeciągnąć, aby dodać obraz",
      cancel: "anulować",
      saveim: "zapisać obraz",
      deleteim: "usunąć obraz",
      imagetxt:
        "Zdjęcie profilowe to pierwsze zdjęcie na poniższej liście. Klikając na inne zdjęcie, ustawiasz je jako główne.",
      max: "Osiągnąłeś maksymalny obraz.Możesz usunąć stary i przesłać nowy obraz",
      desc: "opis",
      del: "kasować",
      main: "główny",
      save: "zapisać",
    },
    err: {
      unrec: "Nierozpoznany błąd",
      largeimg: "Duży plik obrazu",
      onlyimg: "Tylko plik obrazu",
      emailerr: "Pole Email jest wymagane i musi być prawidłowe",
      passerr: "Pole HASŁO jest wymagane i musi mieć co najmniej 8 znaków",
      nameerr: "Pole NAZWA jest wymagane",
      aliaserr:
        "Pole ALIAS jest wymagane i musi zawierać tylko angielskie znaki i cyfry i nie może być tylko liczbą",
      something: "Coś poszło nie tak",
      sessionerr: "Sesja się skończyła",
      socialerr: "Pola TITLE i VALUE są wymagane",
      logpas: "Nieprawidłowy EMAIL lub HASŁO",
      largeonly: "Plik jest za duży lub nie ma obrazu",
      image10: "Maksymalna liczba zdjęć to 10",
      cat1: "Kategoria jest wymagana. Najpierw umieść potrzebną kategorię, a następnie usuń tę.",
      cat3: "Maksymalna liczba kategorii to 3.",
      bufer: "pomyślnie skopiowano do schowka",
      succ: "pomyślnie",
      sentmail: "Nazwa Temat Wiadomość są wymagane",
      strname: "Pole Nazwa strumienia jest wymagane",
      nouser: "użytkownik nie znaleziony",
      olduser: "może ten użytkownik już istnieje",
    },
    time: {
      h: "g",
      m: "m",
    },
    video: {
      first: "Film jest chwilowo niedostępny",
      second: "Przepraszam za niedogodności",
      blur: "plama",
      voloff: "dźwięk jest wyłączony",
    },
    goback: {
      goback: "Wróć",
    },
    politic: {
      main: "Klikając „Akceptuj wszystkie pliki cookie”, zgadzasz się na przechowywanie plików cookie na swoim urządzeniu w celu usprawnienia nawigacji w witrynie i analizy korzystania z witryny.",
      activetxt:
        "Te pliki cookie są niezbędne do działania witryny i nie można ich wyłączyć w naszych systemach. Zwykle są one ustawiane tylko w odpowiedzi na wykonane przez Ciebie czynności, które stanowią żądanie usług, takie jak ustawienie preferencji prywatności, logowanie lub wypełnianie formularzy. Możesz ustawić przeglądarkę tak, aby blokowała lub ostrzegała Cię o tych plikach cookie, ale niektóre części witryny nie będą wtedy działać.",
      activetxtmain:
        "Te pliki cookie nie przechowują żadnych informacji umożliwiających identyfikację osoby.",
      lang: "Przechowywanie informacji o wybranym języku tekstu. Dla ułatwienia nawigacji na stronie",
      city: "Przechowywanie informacji o wybranym mieście. Dla wygody znajdowania zakładów.",
      user: "Przechowywanie informacji o użytkowniku wchodzącym na konto osobiste. Dla wygody logowania się na swoje konto.",
      active: "Zawsze aktywny",
      insettings: "W ustawieniach przeglądarki",
      warried: "Dbamy o twoje dane osobowe",
      accept: "Zaakceptuj wszystkie pliki cookie",
      reject: "Odrzuć wszystko",
      loc: "Dane geolokalizacyjne. Kiedy po raz pierwszy wchodzisz na stronę, wyświetla się okno, w którym możesz wyrazić zgodę na wykorzystanie Twojej lokalizacji. Nie przechowujemy tych danych, a jedynie wykorzystujemy je do dokładniejszego wyboru zakładów i wyświetlania informacji o odległości. Możesz wyłączyć tę funkcjonalność w ustawieniach swojej przeglądarki.",
      ok: "Zaznajomieni",
    },
    map: {
      working: "Pracują",
    },
  },
  ua: {
    header: {
      all: "Все",
      map: "Карта",
      info: "Інфо",
      profile: "профіль",
      login: "Вхід",
      categories: "категорії",
      allDd: "Все",
      search: "Пошук",
      home: "На головну",
      logout: "вихід",
      language: "мова",
      cities: "міста ",
      filters: "фільтри",
    },
    block: {
      type: "тип",
      hours: "години",
      distance: "відстань",
      address: "адрес",
      online: "онлайн",
      km: "км",
    },
    company: {
      stream: "трансляція",
      schedule: "розклад",
      description: "опис",
      contacts: "контакти",
      gallery: "галерея",
      name: "назва",
      type: "категорія",
      hours: "години",
      distance: "відстань",
      address: "адрес",
      Mon: "Пн",
      Tue: "Вт",
      Wed: "Ср",
      Thu: "Чт",
      Fri: "Пт",
      Sat: "Сб",
      Sun: "Нд",
      adult:
        "Вам має бути 18 або більше років, щоб переглядати вміст цієї сторінки",
      yes: "Так, мені 18 або більше років",
      no: "I am not yet 18 years old",
      worktime: "години роботи",
      novideo: "це відео недоступне",
    },
    login: {
      login: "вхід",
      password: "пароль",
    },
    info: {
      "about us": "про нас",
      faq: "запитання ",
      contacts: "контакти",
      name: "i'мя",
      email: "email",
      subject: "об'єкт",
      message: "повідомлення",
      send: "надіслати повідомлення",
      change: "Змінити файли",
      upload: "Завантажити файли",
    },
    list: {
      addplace: "додати місце",
      settings: "сайти та категорії",
      logout: "вихід",
      name: "назва",
      alias: "псевдонім",
      city: "Місто",
      type: "тип",
      delete: "видалити",
      create: "створити",
      createnew: "створити нове місце",
      yes: "так",
      hidequestion: "чи ви дійсно хочете приховати?",
      password: "пароль",
      save: "зберегти",
      edituser: "редагувати користувача",
      adduser: "додати користувача",
      add: "додати",
      delquestion: "ви дійсно хочете видалити",
      hide: "приховати",
      show: "показати",
      olduser: "Старий користувач",
      newuser: "Новий користувач",
      places: "Усі місця цього користувача",
    },
    profile: {
      address: "адрес",
      name: "назва",
      alias: "псевдонім",
      description: "опис",
      save: "зберегти",
      cancel: "скасувати",
      saveloc: "зберегти розташування",
      title: "заголовок",
      value: "значення",
      titlebig: "Заголовок (телефон, вебсайт, ...)",
      valuebig: "Значення (https://example.com)",
      main: "головна",
      cat: "категорії",
      cities: "міста",
      catmaxmin: "категорії (макс 3 / мiн 1)",
      toplace: "до місця",
      addnew: "Додати новий (номер телефону, вебсайт, iнстаграм)",
      gallery: "Галерея",
      properties: "атрибути",
      contacts: "Контакти",
      adult: "18+ для вікна попередження",
    },
    settings: {
      cities: "Міста",
      name: "назва",
      slug: "slug",
      coords: "координати",
      address: "Адрес",
      del: "вид",
      cat: "категорії",
      addnew: "додати новий",
      editcity: "редагувати місто",
      lat: "lat",
      lon: "lon",
      save: "зберегти",
      editcat: "редагувати категорію",
      createcity: "створити місто",
      geo: "Геолокація (lat;lon)",
      create: "створити",
      createcat: "створити нову категорію",
      delcity: "видалити місто",
      delete: "видалити",
      delcat: "видалити категорію",
    },
    stream: {
      notcreated: "Трансляцію ще не створено ",
      deletestr: "видалити трансляцію",
      link: "Посилання для RTMP камери",
      createstr: "створити трансляцію",
      copylink: "Копіювати посилання до буферу обміну",
      notwork: "Відео не працює",
      blur: "розмиття",
      volon: "звук увімкнено",
      voloff: "звук вимкнено",
      streamname: "назва трансляції",
      ifwant:
        "Якщо ви хочете додати трансляцію, зверніться до служби підтримки на сторінці Інформація - Контакти",
    },
    streamsch: {
      disableto: "Вимкнено до",
      streamto: "трансляція до",
      disable: "Відключит",
      Mon: "Пн",
      Tue: "Вт",
      Wed: "Ср",
      Thu: "Чт",
      Fri: "Пт",
      Sat: "Сб",
      Sun: "Нд",
      closed: "закрито",
      opened: "відкрито",
      startt: "час початку",
      endt: "час закінчення",
      save: "зберегти",
      start: "початок",
      end: "кінець",
      timeto: "час до",
      notcreated: "трансляцію ще не було створено",
    },
    adminnav: {
      profile: "профіль",
      stream: "трансляція",
      worksch: "розклад роботи",
      streamsch: "розклад трансляцій",
    },
    drop: {
      changeim: "змінити зображення",
      addim: "Натисніть або перетягніть щоб додати зображення",
      cancel: "відмінити",
      saveim: "берегти зображення",
      deleteim: "видалити зображення",
      imagetxt:
        "Зображення профілю буде першим зображенням у списку нижче. Натиснувши на першу картинку, ви зробити її основною.",
      max: "Ви досягли максимального розміру зображення. Ви можете видалити одне старе зображення, та завантажити одне нове зображення.",
      desc: "опис",
      del: "видалити",
      main: "головна",
      save: "зберегти",
    },
    err: {
      unrec: "нерозпізнана помилка",
      largeimg: "Завеликий розмір зображення",
      image10: "Максимальна кількість зображеннь",
      onlyimg: "тільки файл з зображенням",
      largeonly: "Файл занадто великий за обсягом або не містить зображення",
      emailerr: "Поле для електронної пошти є обов'язковим і має бути дійсним",
      passerr:
        "Поле для вводу пароля має бути заповнено та містити не менше 8 символів",
      nameerr: "Поле для вводу ім'я обов'язково має бути заповненим",
      aliaserr:
        "Поле Псевдонім є обов’язковим і має містити лише англійські символи та цифри, та не може містити просто цифри.",
      something: "Щось пішло не так",
      sessionerr: "Сесія завершена",
      socialerr: "Поля заголовку та значення є обов'язковими",
      logpas: "Дійсний Email або пароль",
      cat1: "Категорія є обов'язковою.Поставте спочатку потрібну категорію, а потім видаліть цю.",
      cat3: "Максимальна кількість категорій – 3.",
      bufer: "успішно скопійовано до буферу обміну",
      succ: "успішно",
      sentmail: "Назва теми повідомлення є обов'язковою",
      strname: "Назва трансляції є обов'язковою",
      nouser: "користувача не знайдено",
      olduser: "Можливо цього користувача вже зареєстровано",
    },
    time: {
      h: "г",
      m: "хв",
    },
    video: {
      first: "Відео тимчасово недоступне",
      second: "Вибачте за незручності",
      blur: "розмиття",
      voloff: "звук вимкнено",
    },
    goback: {
      goback: "На попередню",
    },
    politic: {
      main: "Натискаючи “Прийняти всі файли cookie”, ви погоджуєтеся на збереження файлів cookie на вашому пристрої для покращення навігації по сайту та аналізу використання сайту.",
      activetxt:
        "Ці файли cookie необхідні для функціонування веб-сайту і не можуть бути вимкнені в наших системах. Зазвичай вони встановлюються лише у відповідь на дії, зроблені вами, які є запитом на послуги, такі як налаштування параметрів конфіденційності, вхід або заповнення форм. Ви можете налаштувати свій браузер так, щоб він блокував або сповіщав вас про ці файли cookie, але деякі частини сайту не працюватимуть.",
      activetxtmain:
        "Ці файли cookie не зберігають жодної персональної інформації.",
      lang: "Зберігання інформації про мову тексту, яку ви вибрали. Для зручності навігації по сайту",
      city: "Зберігання інформації про місто, яке ви вибрали. Для зручності пошуку закладів",
      user: "Зберігання інформації про входження користувача в особистий кабінет. Для зручності входу в обліковий запис.",
      active: "Завжди активнийe",
      insettings: "У налаштуваннях браузера",
      warried: "Ми будемо турбуватися про вашу особисту інформацію",
      accept: "Прийняти всі файли cookie",
      reject: "Відхилити всі",
      loc: "Дані геолокації. Коли ви вперше заходите на сайт, вам з’являється вікно для згоди на використання вашого місцезнаходження. Ми не зберігаємо ці дані, а лише використовуємо їх для більш точного вибору закладів та відображення інформації про відстань. Ви можете вимкнути цю функцію в налаштуваннях свого браузера.",
      ok: "Ознайомлений",
    },
    map: {
      working: "Працює",
    },
  },
};
